config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
  
  devise_for :users
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user
    validates :comment, presence: true

end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy

    validates :title, :body, :author, :tags, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_comment, only: [:edit, :update, :show, :destroy]
    before_action :set_post, only: [:create, :edit, :show, :update, :destroy]
  
    def create
      @comment = @post.comments.create(params[:comment].permit(:comment, :post_id))
      @comment.user_id = current_user.id
  
      respond_to do |format|
        if @comment.save
          format.html { redirect_to post_path(@post) }
          format.js # renders create.js.erb
        else
          format.html { redirect_to post_path(@post), notice: "comment did not save. Please try again."}
          format.js
        end
      end
    end
  
    def new
    end
  
  
    def destroy
      @comment = @post.comments.find(params[:id])
      @comment.destroy
      redirect_to post_path(@post)
    end
  
    def edit
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
    end
  
    def update
      @comment = @post.comments.find(params[:id])
       respond_to do |format|
        if @comment.update(comment_params)
          format.html { redirect_to post_path(@post), notice: 'comment was successfully updated.' }
        else
          format.html { render :edit }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def show
    end
  
    private
  
    def set_post
      @post = Post.find(params[:post_id])
    end
    
    def set_comment
      @comment = Comment.find(params[:id])
    end
  
    def comment_params
      params.require(:comment).permit(:comment, :post_id, :user_id)
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end
    
    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :author, :tags, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    
    def post_author(post)
        user_signed_in? && current_user.id == post.user_id
    end

    def comment_author(comment)
        user_signed_in? && current_user.id == comment.user_id
    end
end

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.user.email %>:</strong> <small><%= time_ago_in_words(comment.created_at) %></small>
          <br/>
          <strong><%= comment.comment %></strong>
        </p>
      </div>
      <nav class="level is-mobile">
        <% if comment_author(comment)%>
          <div class="level-left">
            <a class="level-item">
              <%= link_to 'Edit', edit_post_comment_path(comment.post, comment), class: "button" %>
            </a>
            <a class="level-item">
              <%= link_to 'Delete', [comment.post, comment], method: :delete, data: {confirm: "Are you sure ?" }, class: "button" %>
            </a>
          </div>
        <% end %>
      </nav>
    </div>
  </article>
</div>

app/views/comments/_form.html.erb
 <%= simple_form_for([@post, @post.comments.build], remote: true) do |f| %>

<div class="field">
  <div class="control">
    <%= f.input :comment, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' } %>
  </div>
</div>

<%= f.button :submit, 'Leave a comment', class:'button is-info' %>
<% end %>

app/views/comments/create.js.erb
$("<%= escape_javascript(render(@reply)) %>").appendTo('#post-comments');

app/views/comments/edit.html.erb
<h1 class="title is-2 has-text-grey">Editing Comment</h1>

<%= simple_form_for([@post, @comment]) do |f| %>
<div class="field">
  <div class="control">
    <%= f.input :comment, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' } %>
  </div>
</div>

  <%= f.button :submit, 'Update', class:'button is-info' %>
<% end %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%= link_to 'Blog App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in?%>
          <li class="nav-item">
            <%= link_to "Posts", posts_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Add Post", new_post_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link"%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Hello World</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>Blog App</title>
    <%= csrf_meta_tags %> 
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%=  render 'home/header' %>
    <div class="container">
      <br/>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>

      <br/>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if post_author(@post) %>
  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>

  <div class="field form-group">
    <%= form.label :body %>
    <%= form.text_field :body, class: "form-control", placeholder: "Body" %>
  </div>

  <div class="field form-group">
    <% form.label :author %>
    <%= form.text_field :author, class: "form-control", value: current_user.email, type: :hidden %>
  </div>

  <div class="field form-group">
    <%= form.label :tags %>
    <%= form.text_field :tags, class: "form-control", placeholder: "Tags", :required => true %>
  </div>

  <div class="field form-group">
    <%= form.text_field :user_id, id: :posts_user_id, class: "form-control", value: current_user.id, type: :hidden %>
  </div>
  <% else %>
    <div class="field form-group">
    <%= form.label :tags %>
    <%= form.text_field :tags, class: "form-control", placeholder: "Tags", :required => true %>
  </div>
  <% end %>
  <br/>
  <div class="actions">
    <%= form.submit class:'btn btn-secondary'%>
  </div>
<% end %>

app/views/posts/edit.html.erb
<strong>Editing Post</strong>

<%= render 'form', post: @post %>

<br/>
<%= link_to 'Show', @post, class: "btn btn-outline-primary btn-sm" %> |
<%= link_to 'Back', posts_path, class: "btn btn-outline-primary btn-sm" %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<div class="album text-muted">
   <div class="container">
      <div class="row">
         <% @posts.each do |post| %>
         <div class="card">
            <strong class="card-text">Title: <%= link_to post.title, post %></strong>
            <p class="card-text"><strong>By: </strong><%= post.author %></p>
            <p class="card-text"><strong>Content: </strong><%= post.body %></p>
            <p class="card-text"><strong>Tags: </strong><%= post.tags %></p>
         </div>
         <% end %>
      </div>  
   </div>
</div>

<br>

<%= link_to 'New Post', new_post_path, class: "btn btn-secondary" %>

app/views/posts/new.html.erb
<div class="card">
    <div class="card-header">
        <h4>Add New Post</h4>
    </div>
    <div class="card-body">
    <%= render 'form', post: @post %>
    </div>
</div>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="columns">
  <div class="column is-8">
    <h1 class="title is-2 has-text-grey discussion-title"><%= @post.title %></h1>
    <h3 class="subtitle is-5 has-text-grey-lighter">by <%= @post.user.email %></h3>
    <div class="level">
    <strong>Content: <%= @post.body %></strong>
      <div class="level-left"></div>
      <div class="level-right">
        <% if post_author(@post) %>
        <div class="buttons">
            <%= link_to 'Edit', edit_post_path(@post), class:'button'%>
            <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Delete post?" }, class:'button' %>
        </div>
        <% else %>
          <div class="buttons">
            <%= link_to 'Edit', edit_post_path(@post), class:'button'%>
        </div>
        <% end %>
      </div>
    </div>
    <h3><strong>Tags: </strong><%= @post.tags %></h3>
    <br/>
    <h2 class="subtitle is-5 has-text-grey"><%= @post.comments.count %> Comments </h2>

    <div id="discussion-replies">
      <%= render @post.comments %>
    </div>

    <hr />

    <h3 class="subtitle is-3 has-text-grey">Leave a Comment</h3>
    <% if user_signed_in? %>
      <%= render 'comments/form' %>
    <% else %>
    <p>To reply you need to <%= link_to 'login', new_user_session_path %>. Don't have an account?
      <%= link_to 'Sign up', new_user_registration_path %> for one.</p>
    <% end %>

  </div>
</div>